### ISSUE TITLE
About Graphics Memory

### ISSUE THREAD

**Issue by jly0810** [KAIST-Visual-AI-Group/PDS#3]
Hello, your achievement is great. Can I use a 24G RTX3090 graphics card to run your 3D editing work?

**Comment by 63days** [comment]
Dear jiy0810,
Thank you for your interest in our work!

NeRF editing can be run with two GPUs, each having around 24GB VRAM, using a multi-GPU option.
However, in your case, since you have a single 24GB GPU, you can try 3D Gaussian Splat editing, which takes only around 1~2GB VRAM.

Check out the `pds_splat` command in https://github.com/KAIST-Visual-AI-Group/PDS/tree/main/3d_editing/README.md.

Best,
Juil Koo
